export const UPDATE_POSTS = "UPDATE_POSTS";
export const REMOVE_POST = "REMOVE_POST";
export const SET_CURRENT_POST = "SET_CURRENT_POST";
export const ADD_POST = "ADD_POST";
export const LOADING = "LOADING";

export const ADD_FAVORITE = "ADD_FAVORITE";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";
export const UPDATE_FAVORITES = "UPDATE_FAVORITES";

//Cloudinary Constants
export const PHOTOS_FETCHED = 'PHOTOS_FETCHED';
export const PHOTOS_UPLOADED = 'PHOTOS_UPLOADED';
export const DELETE_UPLOADED_PHOTO = 'DELETE_UPLOADED_PHOTO';
export const UPDATE_UPLOADED_PHOTO = 'UPDATE_UPLOADED_PHOTO';